### ISSUE TITLE
Just a little report

### ISSUE THREAD

**Issue by ArseniyShestakov** [kerbyj/goLazagne#2]
It's funny. I've been working on rewriting [ffpass](https://github.com/louisabraham/ffpass) from Python to Go since I did not find any implementation in Go and I need password import tool for my project.

Now I accidentally stumbled upon your repository and here is small quirk:
https://github.com/kerbyj/goLazagne/blob/7771a39ed1779f1093959c34e0ccf22e0ff0eafc/browsers/mozillaGoLazagne.go#L133
For today's Firefox it must be:
```
		her                       = []byte{0x02, 0x02}
```

**Comment by kerbyj** [comment]
Hello! Thank for your issue, really appreciate it.
I saw that the firefox module stopped working. But unfortunately could not catch such a small bug due to lack of time. 
And I just fixed this in 5559439ab96e69d38ecbfab4c2cd5548c2c79114
If the fix is incomplete and there are more bugs, please add more details.
